### ISSUE TITLE
类型错误？？

### ISSUE THREAD

**Issue by lypingk** [SpaceLearner/SessionRec-pytorch#2]
Traceback (most recent call last):
  File "E:/WorkSpace2--pycharm/MHISG-SessionRec-pytorch-main/src/scripts/main_msgifsr.py", line 137, in <module>
    mrr, hit = runner.train(args.epochs, args.log_interval)
  File "E:\WorkSpace2--pycharm\MHISG-SessionRec-pytorch-main\src\utils\train.py", line 96, in train
    mrr, hit = evaluate(self.model, self.test_loader, self.device)
  File "E:\WorkSpace2--pycharm\MHISG-SessionRec-pytorch-main\src\utils\train.py", line 49, in evaluate
    logits = model(*inputs)
  File "E:\requireSoft\anaconda_37\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\WorkSpace2--pycharm\MHISG-SessionRec-pytorch-main\src\models\msgifsr.py", line 246, in forward
    feat = self.embeddings(iid)
  File "E:\requireSoft\anaconda_37\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "E:\requireSoft\anaconda_37\lib\site-packages\torch\nn\modules\sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "E:\requireSoft\anaconda_37\lib\site-packages\torch\nn\functional.py", line 1813, in embedding
    _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
  File "E:\requireSoft\anaconda_37\lib\site-packages\torch\nn\functional.py", line 1733, in _no_grad_embedding_renorm_
    torch.embedding_renorm_(weight, input, max_norm, norm_type)
RuntimeError: Expected tensor for argument #2 'indices' to have scalar type Long; but got torch.IntTensor instead (while checking arguments for embedding_renorm_)
有哪位大神知道怎么改嘛？

**Comment by SpaceLearner** [comment]
Please refer to issue#1
